version: '3.4'

services:
  frontend:
    image: skypeclonevue-frontend
    build:
      context: ./skype-clone-vue-frontend
      dockerfile: ./Dockerfile
    environment:
      - SERVER_URL:https://192.168.43.106:8001
    ports:
      - 8085:8080
  backend:
    image: skypeclonevue-backend
    build:
      context: ./skype-clone-vue-backend
      dockerfile: ./Dockerfile
    environment:
      - CLIENT_URL:https://192.168.43.106:8085
      - DATABASE_URL=mongodb://mongo:27017/slack-clone-db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8001:8000
    restart: unless-stopped
  redis:
    image: redis
    container_name: skypeclonevue-redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    restart: always
  mongo:
    container_name: skypeclonevue-mongodb
    image: mongo:latest
    ports:
      - 27019:27017
    volumes:
      - mongodb:/data/db
    restart: always
volumes:
  mongodb: